# Generated by Django 4.2.4 on 2023-09-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField()),
                ('car_type', models.TextField()),
                ('price', models.IntegerField()),
                ('reservation_memo', models.TextField()),
                ('reservation_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
