# Generated by Django 4.2.4 on 2023-08-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usergrade',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userpoint',
            old_name='user_id',
            new_name='user',
        ),
    ]
