# Generated by Django 4.2.4 on 2023-08-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_id_userauth_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_detail',
            field=models.TextField(null=True),
        ),
    ]
