# Generated by Django 4.2.4 on 2023-08-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_address_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_detail',
            field=models.TextField(default=''),
        ),
    ]
