# Generated by Django 4.2.4 on 2023-09-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
