# Generated by Django 4.2.4 on 2023-09-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.TextField(),
        ),
    ]
